name: build documentation and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: build documentation
        run: make html
      - run: touch _build/html/.nojekyll
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '_build/html'
          destination-github-username: 'mark-nicol'
          destination-repository-name: 'test-public-docs-output''
          user-email: mark-nicol@stfc.ac.uk
          target-branch: gh-pages
          target-directory: docs
